### ISSUE TITLE
Missing 2.10.0 release?

### ISSUE THREAD

**Issue by PascalSchumacher** [FasterXML/jackson-datatype-json-org#17]
Only `2.10.0.pr3` is available from maven central. Other Jackson `2.10.0` artifacts are available and https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10 states that Jackson 2.10 was released today.

**Comment by cowtowncoder** [comment]
Yes, Sonatype's OSSRH had a really REALLY bad day, and half of release was delayed.

If possible, you may want to follow `@FasterXML` on Twitter to get updates on process.

All components finally made their way to MC, but it took almost 24h.
